# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [26]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [27]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [28]:
url="https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data"
data = pd.read_csv(url, sep = "\s+", parse_dates = [[0,1,2]]) 
data.head()

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\3049779939.py:2: SyntaxWarning: invalid escape sequence '\s'
  data = pd.read_csv(url, sep = "\s+", parse_dates = [[0,1,2]])
C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\3049779939.py:2: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  data = pd.read_csv(url, sep = "\s+", parse_dates = [[0,1,2]])
C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\3049779939.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data = pd.read_csv(url, sep = "\s+", parse_dates = [[0,1,2]])

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   datetime64[ns]
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 667.8 KB

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [30]:
import datetime
def fix_date(x):
    year = x.year - 100 if x.year > 1989 else x.year
    return datetime.date(year, x.month, x.day)
data['Yr_Mo_Dy']=data['Yr_Mo_Dy'].apply(fix_date)

In [31]:
data

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [32]:
# data['Yr_Mo_Dy']=pd.to_datetime(data['Yr_Mo_Dy'])
# data['Yr']=data['Yr_Mo_Dy'].dt.year
# data['Mo']=data['Mo'].dt.month
# data['Dy']=data['Dy'].dt.day
# data.head()

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [36]:
data['Yr_Mo_Dy']=pd.to_datetime(data['Yr_Mo_Dy'])
data['Yr']=data['Yr_Mo_Dy'].dt.year
data['Mo']=data['Yr_Mo_Dy'].dt.month
data['Dy']=data['Yr_Mo_Dy'].dt.day
data=data.set_index('Yr_Mo_Dy')
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,Yr,Mo,Dy
Yr_Mo_Dy,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961,1,1
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,1961,1,2
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1961,1,3
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1961,1,4
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,1961,1,5

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [38]:
data.isna().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
Yr     0
Mo     0
Dy     0
dtype: int64

In [39]:
data=data.dropna(subset=['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO'])
data

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,Yr,Mo,Dy
Yr_Mo_Dy,,,,,,,,,,,,,,,
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1961,1,4
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,1961,1,5
1961-01-06,13.21,8.12,9.96,6.67,5.37,4.50,10.67,4.42,7.17,7.50,8.12,13.17,1961,1,6
1961-01-07,13.50,14.29,9.50,4.96,12.29,8.33,9.17,9.29,7.58,7.96,13.96,13.79,1961,1,7
1961-01-08,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46,1961,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08,1978,12,27
1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46,1978,12,28
1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58,1978,12,29
1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79,1978,12,30
1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08,1978,12,31

### Step 7. Compute how many non-missing values there are in total.

In [40]:
data.notnull().sum()

RPT    6549
VAL    6549
ROS    6549
KIL    6549
SHA    6549
BIR    6549
DUB    6549
CLA    6549
MUL    6549
CLO    6549
BEL    6549
MAL    6546
Yr     6549
Mo     6549
Dy     6549
dtype: int64

In [42]:
data['BEL'].mean()

13.111678118796764

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6549 entries, 1961-01-04 to 1978-12-31
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RPT     6549 non-null   float64
 1   VAL     6549 non-null   float64
 2   ROS     6549 non-null   float64
 3   KIL     6549 non-null   float64
 4   SHA     6549 non-null   float64
 5   BIR     6549 non-null   float64
 6   DUB     6549 non-null   float64
 7   CLA     6549 non-null   float64
 8   MUL     6549 non-null   float64
 9   CLO     6549 non-null   float64
 10  BEL     6549 non-null   float64
 11  MAL     6546 non-null   float64
 12  Yr      6549 non-null   int32
 13  Mo      6549 non-null   int32
 14  Dy      6549 non-null   int32
dtypes: float64(12), int32(3)
memory usage: 741.9 KB

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [53]:
data.notna().sum().sum()/len(data)

14.999541914796152

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [54]:
for i in data.columns:
    if data[i].dtype=='float64':
        print(f'{i}: {data[i].mean()}')

RPT: 12.359769430447395
VAL: 10.639929760268744
ROS: 11.657017865322949
KIL: 6.2996274240342025
SHA: 10.450250419911438
BIR: 7.086165826843794
DUB: 9.793496717056039
CLA: 8.487737059092991
MUL: 8.490954344174684
CLO: 8.698486791876622
BEL: 13.111678118796764
MAL: 15.603128628169875

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [58]:
day_stats=pd.DataFrame()
day_stats['min']=data.min(axis=1)
day_stats['max']=data.max(axis=1)
day_stats['mean']=data.mean(axis=1)
day_stats['std']=data.std(axis=1)
day_stats

             min     max        mean         std
Yr_Mo_Dy
1961-01-04  1.00  1961.0  136.362000  504.781236
1961-01-05  1.00  1961.0  139.637333  503.877109
1961-01-06  1.00  1961.0  137.792000  504.385915
1961-01-07  1.00  1961.0  139.574667  503.895729
1961-01-08  1.00  1961.0  139.723333  503.856918
...          ...     ...         ...         ...
1978-12-27  8.08  1978.0  147.833333  506.357269
1978-12-28  5.00  1978.0  146.653333  506.711433
1978-12-29  8.71  1978.0  146.512000  506.705578
1978-12-30  9.13  1978.0  146.960667  506.580837
1978-12-31  9.59  1978.0  147.055333  506.558027

[6549 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [59]:
data.loc[data.index.month==1].mean()

RPT      14.831609
VAL      12.885389
ROS      13.276275
KIL       7.152477
SHA      11.644467
BIR       8.030561
DUB      11.788336
CLA       9.486962
MUL       9.511501
CLO      10.024069
BEL      14.527848
MAL      18.041826
Yr     1969.576854
Mo        1.000000
Dy       16.048825
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [62]:
data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].groupby(data.index.to_period('A')).mean()

C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\1891272064.py:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'Y' instead.
  data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].groupby(data.index.to_period('A')).mean()

,RPT,VAL,ROS,KIL,SHA,DUB,CLA,MUL,CLO
Yr_Mo_Dy,,,,,,,,,
1961,12.220146,10.221345,11.277281,6.862924,10.767749,9.635439,8.713275,8.585029,9.717719
1962,12.260248,10.135179,11.732727,6.962727,10.690358,11.047355,8.821543,8.335785,9.701433
1963,12.813452,10.836986,12.541151,7.330055,11.724110,11.075699,10.336548,8.903589,10.224438
1964,12.363661,10.920164,12.104372,6.787787,11.454481,10.259153,9.467350,7.789016,10.207951
1965,12.451370,11.075534,11.848767,6.858466,11.024795,10.618712,8.879918,7.907425,9.918082
1966,13.461973,11.557205,12.020630,7.345726,11.805041,10.579808,8.835096,8.514438,9.768959
1967,12.737151,10.990986,11.739397,7.143425,11.630740,10.652027,9.325616,8.645014,9.547425
1968,11.835628,10.468197,11.409754,6.477678,10.760765,8.859180,8.255519,7.224945,7.832978
1969,11.166356,9.723699,10.902000,5.767973,9.873918,8.564493,7.711397,7.924521,7.754384
1970,12.600329,10.726932,11.730247,6.217178,10.567370,9.609890,8.334630,9.297616,8.289808
1971,11.273123,9.095178,11.088329,5.241507,9.440329,8.385890,6.757315,7.915370,7.229753
1972,12.463962,10.561311,12.058333,5.929699,9.430410,9.704508,7.680792,8.357295,7.515273
1973,11.828466,10.680493,10.680493,5.547863,9.640877,8.482110,7.614274,8.245534,7.812411
1974,13.643096,11.811781,12.336356,6.427041,11.110986,10.084603,9.896986,9.331753,8.736356
1975,12.008575,10.293836,11.564712,5.269096,9.190082,8.562603,7.843836,8.797945,7.382822
1976,11.737842,10.203115,10.761230,5.109426,8.846339,9.149126,7.146202,8.883716,7.883087
1977,13.099616,11.144493,12.627836,6.073945,10.003836,11.523205,8.378384,9.098192,8.821616
1978,12.504356,11.044274,11.380000,6.082356,10.167233,9.489342,8.800466,9.089753,8.301699

In [66]:
yearly=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('A').mean()
yearly

C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\3829501350.py:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  yearly=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('A').mean()

,RPT,VAL,ROS,KIL,SHA,DUB,CLA,MUL,CLO
Yr_Mo_Dy,,,,,,,,,
1961-12-31,12.220146,10.221345,11.277281,6.862924,10.767749,9.635439,8.713275,8.585029,9.717719
1962-12-31,12.260248,10.135179,11.732727,6.962727,10.690358,11.047355,8.821543,8.335785,9.701433
1963-12-31,12.813452,10.836986,12.541151,7.330055,11.724110,11.075699,10.336548,8.903589,10.224438
1964-12-31,12.363661,10.920164,12.104372,6.787787,11.454481,10.259153,9.467350,7.789016,10.207951
1965-12-31,12.451370,11.075534,11.848767,6.858466,11.024795,10.618712,8.879918,7.907425,9.918082
1966-12-31,13.461973,11.557205,12.020630,7.345726,11.805041,10.579808,8.835096,8.514438,9.768959
1967-12-31,12.737151,10.990986,11.739397,7.143425,11.630740,10.652027,9.325616,8.645014,9.547425
1968-12-31,11.835628,10.468197,11.409754,6.477678,10.760765,8.859180,8.255519,7.224945,7.832978
1969-12-31,11.166356,9.723699,10.902000,5.767973,9.873918,8.564493,7.711397,7.924521,7.754384
1970-12-31,12.600329,10.726932,11.730247,6.217178,10.567370,9.609890,8.334630,9.297616,8.289808
1971-12-31,11.273123,9.095178,11.088329,5.241507,9.440329,8.385890,6.757315,7.915370,7.229753
1972-12-31,12.463962,10.561311,12.058333,5.929699,9.430410,9.704508,7.680792,8.357295,7.515273
1973-12-31,11.828466,10.680493,10.680493,5.547863,9.640877,8.482110,7.614274,8.245534,7.812411
1974-12-31,13.643096,11.811781,12.336356,6.427041,11.110986,10.084603,9.896986,9.331753,8.736356
1975-12-31,12.008575,10.293836,11.564712,5.269096,9.190082,8.562603,7.843836,8.797945,7.382822
1976-12-31,11.737842,10.203115,10.761230,5.109426,8.846339,9.149126,7.146202,8.883716,7.883087
1977-12-31,13.099616,11.144493,12.627836,6.073945,10.003836,11.523205,8.378384,9.098192,8.821616
1978-12-31,12.504356,11.044274,11.380000,6.082356,10.167233,9.489342,8.800466,9.089753,8.301699

### Step 13. Downsample the record to a monthly frequency for each location.

In [63]:
data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].groupby(data.index.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,DUB,CLA,MUL,CLO
Yr_Mo_Dy,,,,,,,,,
1961-01,14.506154,11.225385,12.960385,6.840000,10.509231,10.403077,8.670769,8.323462,9.490385
1961-02,16.401923,15.037308,14.470000,9.242692,13.778077,11.868077,11.746154,11.748462,12.626538
1961-03,10.660000,11.097407,10.420000,7.100741,10.265556,9.108519,9.329259,10.100000,10.989630
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.925333,7.094667,7.342333,7.237000
1961-05,10.024643,8.495714,10.539286,5.992500,9.480357,7.645714,8.206786,8.120714,8.534643
...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.650323,5.417742,7.241290,5.536774
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,10.790333,9.583000,10.069333,8.939000
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,8.115484,7.337742,8.297742,8.243871
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,11.492333,9.657333,10.701333,10.676000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,12.077419,10.194839,10.616774,11.028710

In [68]:
monthly=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('M').mean()
monthly

C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\1367552774.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('M').mean()

,RPT,VAL,ROS,KIL,SHA,DUB,CLA,MUL,CLO
Yr_Mo_Dy,,,,,,,,,
1961-01-31,14.506154,11.225385,12.960385,6.840000,10.509231,10.403077,8.670769,8.323462,9.490385
1961-02-28,16.401923,15.037308,14.470000,9.242692,13.778077,11.868077,11.746154,11.748462,12.626538
1961-03-31,10.660000,11.097407,10.420000,7.100741,10.265556,9.108519,9.329259,10.100000,10.989630
1961-04-30,10.722667,9.427667,9.998000,5.830667,8.435000,6.925333,7.094667,7.342333,7.237000
1961-05-31,10.024643,8.495714,10.539286,5.992500,9.480357,7.645714,8.206786,8.120714,8.534643
...,...,...,...,...,...,...,...,...,...
1978-08-31,9.645161,8.259355,9.032258,4.502903,7.368065,5.650323,5.417742,7.241290,5.536774
1978-09-30,10.913667,10.895000,10.635000,5.725000,10.372000,10.790333,9.583000,10.069333,8.939000
1978-10-31,9.897742,8.670968,9.295806,4.721290,8.525161,8.115484,7.337742,8.297742,8.243871
1978-11-30,16.151667,14.802667,13.508000,7.317333,11.475000,11.492333,9.657333,10.701333,10.676000
1978-12-31,16.175484,13.748065,15.635161,7.094839,11.398710,12.077419,10.194839,10.616774,11.028710

### Step 14. Downsample the record to a weekly frequency for each location.

In [64]:
data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].groupby(data.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,DUB,CLA,MUL,CLO
Yr_Mo_Dy,,,,,,,,,
1961-01-02/1961-01-08,12.316000,10.408000,10.050000,5.658000,8.506000,10.936000,5.932000,8.150000,8.428000
1961-01-09/1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,7.535714,6.820000,5.712857,7.571429
1961-01-16/1961-01-22,12.100000,9.500000,11.681667,4.293333,8.966667,7.828333,7.291667,5.891667,6.693333
1961-01-23/1961-01-29,19.880000,14.846667,17.548333,11.916667,16.325000,14.450000,14.311667,13.316667,14.921667
1961-01-30/1961-02-05,16.827143,15.460000,12.618571,8.247143,13.361429,12.204286,8.548571,9.821429,9.460000
...,...,...,...,...,...,...,...,...,...
1978-11-27/1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,9.642857,7.685714,9.011429,9.547143
1978-12-04/1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,14.437143,12.488571,13.870000,14.082857
1978-12-11/1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,10.208571,7.967143,9.168571,8.565714
1978-12-18/1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,7.798571,8.667143,7.151429,8.072857
1978-12-25/1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,13.708571,10.477143,10.868571,11.471429

In [70]:
weekly=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('W').mean()
weekly

,RPT,VAL,ROS,KIL,SHA,DUB,CLA,MUL,CLO
Yr_Mo_Dy,,,,,,,,,
1961-01-08,12.316000,10.408000,10.050000,5.658000,8.506000,10.936000,5.932000,8.150000,8.428000
1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,7.535714,6.820000,5.712857,7.571429
1961-01-22,12.100000,9.500000,11.681667,4.293333,8.966667,7.828333,7.291667,5.891667,6.693333
1961-01-29,19.880000,14.846667,17.548333,11.916667,16.325000,14.450000,14.311667,13.316667,14.921667
1961-02-05,16.827143,15.460000,12.618571,8.247143,13.361429,12.204286,8.548571,9.821429,9.460000
...,...,...,...,...,...,...,...,...,...
1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,9.642857,7.685714,9.011429,9.547143
1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,14.437143,12.488571,13.870000,14.082857
1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,10.208571,7.967143,9.168571,8.565714
1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,7.798571,8.667143,7.151429,8.072857
1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,13.708571,10.477143,10.868571,11.471429

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [77]:
weekly_data=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('W').agg([min,max,np.mean,np.std])

weekly_data.loc[weekly_data.index[1:53],'RPT':'CLO']

C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\1617428134.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  weekly_data=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('W').agg([min,max,np.mean,np.std])
C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\1617428134.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  weekly_data=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('W').agg([min,max,np.mean,np.std])
C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\1617428134.py:1: FutureWarning: The provided callable <function mean at 0x00000227557D8900> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  weekly_data=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('W').agg([min,max,np.mean,np.std])
C:\Users\mohit\AppData\Local\Temp\ipykernel_3656\1617428134.py:1: FutureWarning: The provided callable <function std at 0x00000227557D8A40> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  weekly_data=data[['RPT','VAL','ROS','KIL','SHA','DUB','CLA','MUL','CLO']].resample('W').agg([min,max,np.mean,np.std])

              RPT                                VAL                    \
              min    max       mean       std    min    max       mean
Yr_Mo_Dy
1961-01-15   9.04  19.75  12.468571  3.555392   3.54  12.08   8.967143
1961-01-22   4.92  17.75  12.100000  4.893064   3.42  14.37   9.500000
1961-01-29  13.62  25.04  19.880000  4.619061   9.96  20.79  14.846667
1961-02-05  10.58  24.21  16.827143  5.251408   9.46  24.21  15.460000
1961-02-12  16.00  24.54  19.684286  3.587677  11.54  21.42  16.417143
1961-02-19   6.04  22.50  14.956667  5.525210  11.63  20.17  15.008333
1961-02-26   7.79  25.80  15.221429  7.020716   7.08  21.50  13.625714
1961-03-05  10.96  13.33  11.824000  1.071742   8.83  17.00  12.956000
1961-03-12   4.88  14.79   9.376667  3.732263   8.08  16.96  11.195000
1961-03-19   4.92  16.88  11.911429  3.860036   9.46  15.54  13.501429
1961-03-26   6.29  15.00   9.567143  3.613298   2.58  11.63   8.387143
1961-04-02   5.88  18.25   9.818000  4.853908   3.50  16.29   7.684000
1961-04-09   4.50  18.12  11.964286  4.604392   7.04  14.62  10.654286
1961-04-16   4.71  15.50   8.965714  3.937727   4.83  12.25   8.000000
1961-04-23   4.00  21.09  12.621429  5.676655   3.71  15.41  10.438571
1961-04-30   4.08  16.29  10.117143  4.349662   6.50  14.46   9.798571
1961-05-07   9.87  23.00  15.367143  5.025507  10.29  19.79  13.970000
1961-05-14   3.54  12.79   7.901667  3.673850   3.96  11.54   7.645000
1961-05-21   4.88  15.04   8.561667  3.857369   3.58  10.17   5.631667
1961-05-28   4.96  10.92   7.550000  2.433828   3.67  11.17   6.536667
1961-06-04   7.00  15.92  10.321429  3.099701   4.75   9.79   7.407143
1961-06-11   8.29  14.42  10.917143  2.248597   6.83  11.54   8.992857
1961-06-18   6.13  14.33  10.571429  3.009482   4.12  14.54   9.565714
1961-06-25   4.00   9.00   7.345714  1.982035   3.25   9.50   6.108571
1961-07-02   7.21  13.13  10.236667  2.557856   6.34  14.37   9.320000
1961-07-09   7.29  17.50  11.806667  4.005984   3.75  10.75   7.221667
1961-07-16   8.63  22.50  16.680000  5.168710   7.87  19.29  13.518571
1961-07-23   3.04   5.88   4.202857  1.047978   2.92   6.79   4.255714
1961-07-30   6.13  16.08  10.561429  4.157641   4.63  13.79   8.445714
1961-08-06   7.67  16.08  10.870000  2.950887   5.09  15.79   8.792857
1961-08-13   2.88  14.21   9.928000  4.931346   4.42  10.00   8.026000
1961-08-20  13.13  18.91  15.607143  2.283635   7.25  13.62  10.565714
1961-08-27   7.67  18.16  12.391429  3.395857   6.87  14.58  11.430000
1961-09-03   3.63  14.46   8.678571  4.398615   1.13  22.00   8.821429
1961-09-10   5.00  17.62  10.541429  5.207278   3.04  13.59   8.798571
1961-09-17   5.33  28.75  17.160000  7.679190   7.12  22.08  14.440000
1961-09-24   6.92  10.25   8.291667  1.250191   2.92  13.62   7.645000
1961-10-01  10.34  19.12  14.850000  3.600911   6.96  13.62  11.361667
1961-10-08   3.13  16.08  11.250000  5.596710   3.63  16.96   8.757143
1961-10-15   3.71  17.12  10.881667  4.780675   6.13  13.25   9.905000
1961-10-22  10.46  28.62  19.260000  7.888314   3.75  19.46  13.364286
1961-10-29   4.33  21.34  14.353333  7.143390   2.75  17.00  10.303333
1961-11-05   5.88  15.79  11.571429  3.369201   3.96  13.46   9.590000
1961-11-12   5.46  16.08  10.428571  3.939811   5.50  10.75   7.690000
1961-11-19   7.50  15.00  10.798571  2.784358   4.21  13.00   7.951429
1961-11-26   5.75  14.29   9.638333  3.229622   3.29  11.79   6.886667
1961-12-03   7.92  23.75  12.608571  5.704669   4.67  18.71  10.442857
1961-12-10  10.83  23.71  17.362857  4.890152   9.21  21.37  14.362857
1961-12-17   9.29  21.34  14.985714  4.095106   8.63  17.62  13.472857
1961-12-24  11.46  24.41  15.757143  4.959717   9.79  16.13  11.971429
1961-12-31   5.04  20.54  13.634286  5.787783   3.08  16.04   9.504286
1962-01-07   3.17  15.04   9.374286  4.080363   3.13  13.04   7.471429

                        ROS         ...        CLA              MUL         \
                 std    min    max  ...       mean       std    min    max
Yr_Mo_Dy                            ...
1961-01-15  3.148945   7.08  19.50  ...   6.820000  3.936894   0.50  10.37
1961-01-22  4.070420   7.29  17.33  ...   7.291667  3.025765   1.92   8.71
1961-01-29  4.242125  12.67  25.84  ...  14.311667  4.191761   7.12  18.66
1961-02-05  5.187395   9.04  19.70  ...   8.548571  4.081158   6.34  13.37
1961-02-12  3.608373  13.67  21.34  ...  14.850000  3.022753  10.37  18.96
1961-02-19  3.908818   6.13  19.41  ...  12.178333  2.497226   8.17  14.88
1961-02-26  5.147348   6.08  22.42  ...  10.875714  4.869668   4.50  18.46
1961-03-05  3.490319   8.17  13.67  ...  10.032000  2.640733   6.25  11.71
1961-03-12  3.359302   7.54  15.50  ...   8.960000  3.621955   5.21  12.46
1961-03-19  2.352867   5.25  13.96  ...  10.220000  3.373421   6.00  13.88
1961-03-26  3.657265   4.79  15.63  ...   8.977143  2.789682   8.00  14.37
1961-04-02  5.130656   5.09  14.96  ...   7.518000  4.534884   6.50  17.54
1961-04-09  2.845399   9.29  18.29  ...   8.041429  1.996609   5.66  10.54
1961-04-16  2.607118   3.92  15.79  ...   4.994286  2.379446   3.37   9.00
1961-04-23  4.631736   3.33  17.00  ...   9.111429  3.935731   3.58  13.29
1961-04-30  2.871425   2.54  14.96  ...   6.377143  3.426255   2.54  11.08
1961-05-07  3.750835   8.42  21.21  ...  12.244286  4.461950   7.79  17.04
1961-05-14  2.755749   4.63  12.33  ...   7.555000  4.927611   2.46  17.33
1961-05-21  2.468906   5.91  15.96  ...   6.868333  2.415777   4.92   9.46
1961-05-28  2.757025   3.58  13.13  ...   5.305000  2.115247   4.50   7.33
1961-06-04  1.868125   6.83  15.96  ...   8.635714  0.915184   6.34  11.17
1961-06-11  1.524836   6.04  11.58  ...   6.884286  2.857527   5.41  10.58
1961-06-18  3.509444   6.50  15.50  ...   9.102857  4.858023   4.21  12.12
1961-06-25  2.212460   5.13  10.37  ...   9.447143  2.109358   6.50  12.92
1961-07-02  3.144201   7.62  10.79  ...   9.200000  3.356325   5.79  10.41
1961-07-09  2.943083   7.62  14.92  ...   9.200000  3.447741   6.25  15.46
1961-07-16  3.849630   8.00  14.29  ...  10.507143  4.083629   2.92  15.37
1961-07-23  1.400010   4.08  12.67  ...   5.642857  1.479152   4.00   6.50
1961-07-30  3.203206   6.42  15.67  ...   9.198571  4.060478   2.21  15.59
1961-08-06  3.985226   5.54  15.59  ...   8.265714  3.921508   3.17  11.67
1961-08-13  2.410960   6.00  11.63  ...   8.330000  2.371782   2.83  10.08
1961-08-20  2.523416   9.17  14.04  ...  11.714286  2.972809   8.79  16.13
1961-08-27  3.174702   9.50  17.83  ...  12.201429  4.900671   3.96  17.50
1961-09-03  7.474025   2.42  12.75  ...   8.612857  5.012759   3.67  13.50
1961-09-10  4.003996   3.63  14.88  ...   6.674286  3.074692   2.50  12.71
1961-09-17  5.360585   7.29  26.50  ...  13.131429  4.565163   5.88  21.34
1961-09-24  3.495865   5.33  12.17  ...   6.881667  3.342247   2.83   7.33
1961-10-01  2.812482   7.87  17.16  ...   9.620000  2.911323   7.00  10.04
1961-10-08  5.060803   4.96  17.83  ...   6.220000  3.313201   1.42  10.58
1961-10-15  2.924338   4.21  20.96  ...   8.155000  2.645439   3.13  11.12
1961-10-22  5.998199   9.92  22.63  ...  12.560000  5.199929   7.38  18.00
1961-10-29  6.021514   4.79  22.88  ...   8.443333  4.380227   4.25  15.37
1961-11-05  3.900278   6.54  14.33  ...   9.970000  3.599111   5.71  15.09
1961-11-12  2.141191   3.83  20.41  ...   4.257143  2.181840   1.33   7.38
1961-11-19  3.208548   6.46  32.71  ...   4.625714  3.452202   0.75  10.37
1961-11-26  3.344994   5.04  14.46  ...   6.918333  2.493900   4.67  10.04
1961-12-03  5.107089   8.00  19.92  ...   6.245714  3.744471   2.25  12.58
1961-12-10  4.115506   9.71  20.54  ...  10.114286  4.503161   5.09  15.12
1961-12-17  3.587886   9.04  19.00  ...  10.428571  3.482027   4.71  17.25
1961-12-24  2.220866   8.08  22.13  ...   7.012857  4.134367   1.25  12.54
1961-12-31  4.566479   2.13  29.33  ...   6.851429  4.289240   1.83  10.37
1962-01-07  4.431006   4.38  12.21  ...   4.661429  4.165123   0.54   9.13

                                   CLO
                 mean       std    min    max       mean       std
Yr_Mo_Dy
1961-01-15   5.712857  3.500975   2.67  14.58   7.571429  4.084293
1961-01-22   5.891667  2.765440   2.71  11.38   6.693333  3.203652
1961-01-29  13.316667  4.179486  11.04  19.08  14.921667  3.494638
1961-02-05   9.821429  2.802490   5.50  13.13   9.460000  2.839501
1961-02-12  14.064286  2.914760  12.25  17.79  14.440000  1.746749
1961-02-19  12.508333  2.778528   9.21  16.58  13.521667  2.772287
1961-02-26  10.392857  4.705163   7.00  20.04  12.730000  4.920064
1961-03-05   9.668000  2.162908   9.79  14.09  12.068000  1.729775
1961-03-12   8.818333  2.546428   5.09  13.54   9.570000  3.065864
1961-03-19  10.101429  3.301880   7.29  15.34  11.627143  3.099472
1961-03-26  10.904286  2.469432   8.33  14.50  11.481429  2.538224
1961-04-02  10.666000  4.470999   6.46  14.21   8.666000  3.193114
1961-04-09   8.161429  1.935058   3.67  10.50   7.238571  2.336182
1961-04-16   5.718571  2.123279   4.00   9.67   6.178571  2.161137
1961-04-23   8.767143  3.656682   3.83  14.37   9.551429  3.347972
1961-04-30   6.242857  2.718926   2.71  11.46   6.124286  2.840568
1961-05-07  11.677143  3.558856   8.63  17.54  11.585714  3.620819
1961-05-14   7.908333  5.507248   1.83  17.92   8.396667  5.745543
1961-05-21   6.821667  1.766380   4.17   9.29   6.855000  2.309283
1961-05-28   5.528333  1.388631   5.17  10.46   6.881667  2.089856
1961-06-04   8.714286  1.954609   5.91  12.04   9.035714  2.096989
1961-06-11   8.034286  1.695090   5.21  10.92   8.397143  2.158323
1961-06-18   8.992857  2.900464   3.08  14.71   9.594286  3.792400
1961-06-25  10.458571  2.042257   7.83  15.00  11.257143  2.286218
1961-07-02   8.041667  1.869764   7.96  12.38  10.160000  1.684292
1961-07-09  10.348333  3.614910   6.21  16.79  10.381667  3.977428
1961-07-16   9.530000  3.978635   4.25  14.92  10.157143  3.271899
1961-07-23   5.297143  0.873207   3.92   7.75   6.041429  1.439785
1961-07-30   8.037143  4.504844   4.92  15.75   9.470000  4.350268
1961-08-06   8.011429  3.217501   5.41  12.83   8.951429  2.903018
1961-08-13   6.466000  3.307556   5.41   9.92   7.632000  2.047833
1961-08-20  11.780000  2.339544   9.13  17.83  12.244286  2.730237
1961-08-27   9.817143  4.120185   7.46  15.96  12.507143  3.855302
1961-09-03   6.744286  4.155931   5.96  16.13   8.924286  3.993736
1961-09-10   6.977143  3.767708   1.75  11.71   7.565714  3.649278
1961-09-17  11.401429  4.847073   9.67  25.21  14.268571  5.128338
1961-09-24   5.151667  1.633468   2.83  10.71   6.896667  2.563058
1961-10-01   8.353333  1.210548   5.29  14.00  10.903333  3.310738
1961-10-08   5.650000  3.717239   2.42  12.21   7.662857  4.296870
1961-10-15   7.765000  2.826997   5.71  15.21  10.181667  3.364375
1961-10-22  13.118571  3.785875  11.08  26.38  16.461429  5.890511
1961-10-29   9.435000  4.448500   5.83  17.75  11.423333  5.257283
1961-11-05  10.172857  3.003274   7.67  15.79  11.864286  2.784450
1961-11-12   5.188571  2.153102   2.62  10.88   6.415714  2.843518
1961-11-19   4.501429  3.488521   1.25  14.04   6.031429  4.402588
1961-11-26   7.035000  2.230720   7.38  14.12  10.026667  2.720968
1961-12-03   7.372857  3.658796   3.63  13.00   7.911429  3.680477
1961-12-10   9.970000  3.452864   5.75  15.50  12.022857  4.156207
1961-12-17  10.655714  4.333020   4.67  17.41  11.058571  4.633398
1961-12-24   5.517143  4.243508   2.46  15.34   7.697143  4.637096
1961-12-31   6.748571  3.325214   1.96  10.83   7.701429  3.526625
1962-01-07   4.572857  3.322518   0.92  13.75   6.475714  4.647207

[52 rows x 36 columns]